services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: tinyurl-api
    ports:
      - "8080:8080"
    environment:
      - SPRING_CASSANDRA_CONTACT_POINTS=cassandra
      - SPRING_CASSANDRA_PORT=9042
      - SPRING_CASSANDRA_LOCAL_DATACENTER=datacenter1
      - SPRING_CASSANDRA_KEYSPACE_NAME=tinyurl
    depends_on:
      cassandra:
        condition: service_healthy
  cassandra:
    image: cassandra:latest
    container_name: cassandra
    ports:
      - "9042:9042"
    environment:
      - CASSANDRA_DC=datacenter1
      - CASSANDRA_CLUSTER_NAME=tinyurl-cluster
    healthcheck:
      test: ["CMD-SHELL", "nodetool status"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - cassandra_data:/var/lib/cassandra
  cassandra-load-keyspace:
    image: cassandra:latest
    depends_on:
      cassandra:
        condition: service_healthy
    volumes:
        - ./api/src/main/resources/scripts/tinyurl-data.cql:/tinyurl-data.cql
    command: /bin/bash -c "echo 'Loading data...'; cqlsh cassandra -f /tinyurl-data.cql"
volumes:
  cassandra_data: